//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Evento
    {
        [Key]
        public int idEvento { get; set; }
        public System.DateTime fecha { get; set; }
        public string lugar { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public int estado { get; set; }
    }
}
